plugins: 
 - jest

env: 
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest

rules: 
  no-console: 0
  no-shadow: 'off'
  # indent: 'off'
  indent: ['error', 4]
  linebreak-style: ['error','windows']
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]